### ISSUE TITLE
Adjust `code` font size at large screen sizes

### ISSUE THREAD

**Issue by katamartin** [carbonplan/theme#64]
When `code` elements are rendered within `p` blocks, the ratio between font-sizes really jumps at the final breakpoint (from `18px : 14px` to `24px : 16px`). This is reflected in the font-sizes array defined for each style:
https://github.com/carbonplan/theme/blob/cae5e9bd72246d8c194debc83c5ba84fd41d3a30/index.js#L109
https://github.com/carbonplan/theme/blob/cae5e9bd72246d8c194debc83c5ba84fd41d3a30/index.js#L225

## Current
<img width="840" alt="CleanShot 2023-12-12 at 12 38 07@2x" src="https://github.com/carbonplan/theme/assets/12436887/6c32b4e9-fc4a-42c2-804d-a5aa3034b76f">

`fontSize: [1, 1, 1, 2]`

## Proposed
<img width="840" alt="CleanShot 2023-12-12 at 12 37 41@2x" src="https://github.com/carbonplan/theme/assets/12436887/429cd962-d0f1-4520-a248-79d6947181bd">

`fontSize: [1, 1, 1, 3]`

**Comment by freeman-lab** [comment]
Certainly looks much better!
